sudo: false # to use faster container based build environment
language: elixir

elixir:
  - 1.7.4
  - 1.8.1
  - 1.9.4
  - 1.10.4

otp_release:
  - 21.2
  - 22.3
  - 23.0

matrix:
  exclude:
    - otp_release: 23.0
      elixir: 1.7.4
    - otp_release: 23.0
      elixir: 1.8.1
    - otp_release: 23.0
      elixir: 1.9.4      

script:
  - MIX_ENV=test mix credo --strict
  - mix format --check-formatted
  - MIX_ENV=test mix coveralls.travis --trace --cover

before_deploy:
  - mix compile
deploy:
  skip_cleanup: true
  provider: script
  script: mix hex.publish --yes
  on:
    tags: true
